using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace NerdDinner.Cqrs
{
    #region Generated by Lokad Code DSL
    [DataContract(Namespace = "NerdDinner")]
    public partial class DinnerId
    {
        [DataMember(Order = 1)] public int Id { get; private set; }
        
        DinnerId () {}
        public DinnerId (int id)
        {
            Id = id;
        }
    }
    [DataContract(Namespace = "NerdDinner")]
    public partial class HostDinner : Command
    {
        [DataMember(Order = 1)] public DinnerId Id { get; private set; }
        [DataMember(Order = 2)] public string HostedBy { get; private set; }
        [DataMember(Order = 3)] public string Title { get; private set; }
        [DataMember(Order = 4)] public DateTime EventDate { get; private set; }
        [DataMember(Order = 5)] public string Description { get; private set; }
        [DataMember(Order = 6)] public string ContactPhone { get; private set; }
        [DataMember(Order = 7)] public string Address { get; private set; }
        [DataMember(Order = 8)] public string Country { get; private set; }
        
        HostDinner () {}
        public HostDinner (DinnerId id, string hostedBy, string title, DateTime eventDate, string description, string contactPhone, string address, string country)
        {
            Id = id;
            HostedBy = hostedBy;
            Title = title;
            EventDate = eventDate;
            Description = description;
            ContactPhone = contactPhone;
            Address = address;
            Country = country;
        }
        
        public override string ToString()
        {
            return string.Format(@"host dinner - {0}", Title);
        }
    }
    
    public interface IDinnerApplicationService
    {
        void When(HostDinner c);
    }
    #endregion
}
